In [34]:
import mxnet
from mxnet import nd
from mxnet import autograd

In [8]:
x = nd.arange(12)
print(x)
print(x.shape)
x = x.reshape(3, 4)
print(x.shape, x.size)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>
(12,)
(3, 4) 12


In [13]:
# nd.zeros((2, 3, 4))
# nd.ones((2, 3))
# Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X = nd.random.normal(0, 1, (3, 4))
Y = nd.random.normal(0, 1, (4, 3))
nd.dot(X, Y)


[[ 0.8914373   0.20784463  0.02696061]
 [ 0.8281651   1.392174   -4.107341  ]
 [-0.88099253  0.52899957 -4.4045634 ]]
<NDArray 3x3 @cpu(0)>

In [17]:
nd.concat(X, Y.T, dim=0)
nd.concat(X, Y.T, dim=1)


[[-0.68106437 -0.1353156   0.37723133  0.41016456 -0.5916499   0.20131476
   1.5194443  -0.14007866]
 [ 0.5712682  -2.7579627   1.07628    -0.6141325   0.85860497  0.3500547
   1.9040879   0.29670075]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806  -0.22794183  0.5360521
  -1.5734432   1.3111951 ]]
<NDArray 3x8 @cpu(0)>

In [22]:
print(X.norm(2))
print(X.norm(2).asscalar())


[4.6063175]
<NDArray 1 @cpu(0)>
4.6063175


In [24]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
print(A)
print(B)


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

[[0. 1.]]
<NDArray 1x2 @cpu(0)>


In [25]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [28]:
print(X)
print(X[1:3])


[[-0.68106437 -0.1353156   0.37723133  0.41016456]
 [ 0.5712682  -2.7579627   1.07628    -0.6141325 ]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

[[ 0.5712682  -2.7579627   1.07628    -0.6141325 ]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806 ]]
<NDArray 2x4 @cpu(0)>


In [32]:
before = id(X)
X = X + Y.T
id(X) == before

False

In [33]:
X.asnumpy()

array([[-1.8643641 ,  0.26731393,  3.41612   ,  0.13000724],
       [ 2.2884781 , -2.0578532 ,  4.8844557 , -0.02073103],
       [ 1.3748811 , -0.07470226, -3.0930486 ,  0.11490965]],
      dtype=float32)

In [35]:
X


[[-1.8643641   0.26731393  3.41612     0.13000724]
 [ 2.2884781  -2.0578532   4.8844557  -0.02073103]
 [ 1.3748811  -0.07470226 -3.0930486   0.11490965]]
<NDArray 3x4 @cpu(0)>

In [36]:
X = nd.arange(4).reshape((4, 1))

In [37]:
X.attach_grad()

In [38]:
with autograd.record():
    y = 2 * nd.dot(X.T, X)

In [39]:
y.backward()

In [40]:
X


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [41]:
X.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [43]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [46]:
def func(a):
    b =  a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    c = func(a)
c.backward()

In [49]:
nd.random.uniform?