In [1]:
import mxnet
from mxnet import nd
from mxnet import autograd
import numpy as np
from time import time

In [32]:
X = np.random.normal(0, 1, [3, 4])
Y = np.random.normal(0, 1, [4, 3])
t0 = time()
np.dot(X, Y)
t1 = time()

X = nd.random.normal(0, 1, [3, 4])
Y = nd.random.normal(0, 1, [4, 3])
t2 = time()
nd.dot(X, Y)
t3 = time()

print(t1 - t0)
print(t3 - t2)

0.0
0.0


In [4]:
x = nd.arange(12)
print(x)
print(x.shape, x.size)

X = x.reshape(3, 4)
print(X)
print(X.shape, X.size)



[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>
(12,) 12

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>
(3, 4) 12


In [7]:
# nd.zeros((2, 3, 4))
# nd.ones((2, 3))
# Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

Y = nd.random.normal(0, 1, (4, 3))
print(Y)
print(nd.dot(X, Y))


[[-0.59164983  0.8586049  -0.22794184]
 [ 0.20131476  0.35005474  0.5360521 ]
 [ 1.5194443   1.9040878  -1.5734432 ]
 [-0.14007865  0.29670078  1.3111951 ]]
<NDArray 4x3 @cpu(0)>

[[ 2.8199675  5.0483327  1.3227513]
 [ 6.7760897 18.686125   1.5062003]
 [10.732213  32.32392    1.6896486]]
<NDArray 3x3 @cpu(0)>


In [8]:
print(nd.concat(X, Y.T, dim=0))
print(nd.concat(X, Y.T, dim=1))


[[ 0.          1.          2.          3.        ]
 [ 4.          5.          6.          7.        ]
 [ 8.          9.         10.         11.        ]
 [-0.59164983  0.20131476  1.5194443  -0.14007865]
 [ 0.8586049   0.35005474  1.9040878   0.29670078]
 [-0.22794184  0.5360521  -1.5734432   1.3111951 ]]
<NDArray 6x4 @cpu(0)>

[[ 0.          1.          2.          3.         -0.59164983  0.20131476
   1.5194443  -0.14007865]
 [ 4.          5.          6.          7.          0.8586049   0.35005474
   1.9040878   0.29670078]
 [ 8.          9.         10.         11.         -0.22794184  0.5360521
  -1.5734432   1.3111951 ]]
<NDArray 3x8 @cpu(0)>


In [9]:
print(X.norm(2))
print(X.norm(2).asscalar())


[22.494442]
<NDArray 1 @cpu(0)>
22.494442


In [12]:
# broadcasting
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
print(A)
print(B)
print(A+B)


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

[[0. 1.]]
<NDArray 1x2 @cpu(0)>

[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>


In [14]:
# index
print(X)
print(X[1:3])


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>


In [31]:
####### NOTE: memory
before = id(X)
X = X + Y.T
print(id(X) == before)

Z = X.zeros_like()
before = id(Z)
Z[:] = X + Y.T  # 实际上会先把结果存着再放到Z中
print(id(Z) == before)

# 最少内存消耗
Z = X.zeros_like()
before = id(Z)
nd.elemwise_add(X, Y.T, out=Z)  # 直接把结果存到Z中
print(id(Z) == before)

False
True
True


In [29]:
# numpy <==> ndarray
print(nd.array(np.ones((2, 3))))
print(X.asnumpy())


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>
[[-3.5498989   2.2078886  11.116667    2.1595287 ]
 [ 9.1516285   7.1003284  17.424528    8.780205  ]
 [ 6.632348   12.2163105   0.55934024 18.867172  ]]


In [32]:
x = nd.arange(4)
print(x)
x = x.reshape([1, 4])
print(x)
x = x.reshape([4, 1])
print(x)


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>

[[0. 1. 2. 3.]]
<NDArray 1x4 @cpu(0)>

[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>


In [ ]:
nd.random.uniform?

In [2]:
X = nd.array([[1, 2, 3], [4, 5, 6]])
print(X)
print(X.sum(axis=0, keepdims=True))
print(X.sum(axis=0, keepdims=False))
print(X.sum(axis=1, keepdims=True))
print(X.sum(axis=1, keepdims=False))


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>

[[5. 7. 9.]]
<NDArray 1x3 @cpu(0)>

[5. 7. 9.]
<NDArray 3 @cpu(0)>

[[ 6.]
 [15.]]
<NDArray 2x1 @cpu(0)>

[ 6. 15.]
<NDArray 2 @cpu(0)>


In [3]:
help(nd.pick)

Help on function pick:

pick(data=None, index=None, axis=_Null, keepdims=_Null, mode=_Null, out=None, name=None, **kwargs)
    Picks elements from an input array according to the input indices along the given axis.
    
    Given an input array of shape ``(d0, d1)`` and indices of shape ``(i0,)``, the result will be
    an output array of shape ``(i0,)`` with::
    
      output[i] = input[i, indices[i]]
    
    By default, if any index mentioned is too large, it is replaced by the index that addresses
    the last element along an axis (the `clip` mode).
    
    This function supports n-dimensional input and (n-1)-dimensional indices arrays.
    
    Examples::
    
      x = [[ 1.,  2.],
           [ 3.,  4.],
           [ 5.,  6.]]
    
      // picks elements with specified indices along axis 0
      pick(x, y=[0,1], 0) = [ 1.,  4.]
    
      // picks elements with specified indices along axis 1
      pick(x, y=[0,1,0], 1) = [ 1.,  4.,  5.]
    
      y = [[ 1.],
           [ 0.